### ISSUE TITLE
Crashing when I start

### ISSUE THREAD

**Issue by sauceaple** [Linguardium/ItemNbtModels#7]
Crash log:
---- Minecraft Crash Report ----
// Don't do that.

Time: 10/28/20 1:24 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'itemnbtmodels'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                  
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:74)
	at me.sargunvohra.mcmods.autoconfig1u.serializer.Toml4jConfigSerializer.deserialize(Toml4jConfigSerializer.java:55)
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.load(ConfigManager.java:52)
	at me.sargunvohra.mcmods.autoconfig1u.ConfigManager.<init>(ConfigManager.java:25)
	at me.sargunvohra.mcmods.autoconfig1u.AutoConfig.register(AutoConfig.java:45)
	at mod.linguardium.itemnbtmodels.Main.onInitializeClient(Main.java:39)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2563/2128651786.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.IllegalStateException: Key is not followed by an equals sign on line 1:                                                                  
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:140)
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:107)
	at me.sargunvohra.mcmods.autoconfig1u.shadowed.com.moandjiezana.toml.Toml.read(Toml.java:72)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 707870376 bytes (675 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.6.0
		fabric: Fabric API 0.24.2+build.413-1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.1+a4467d2a95
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
		fabricloader: Fabric Loader 0.10.5+build.213
		fiber: fiber 0.24.0-dev
		itemnbtmodels: ItemNbtModels 0.1.1
		kami: KAMI 1.16.3-oct
		minecraft: Minecraft 1.16.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		satin: Satin 1.5.0
	Launched Version: fabric-loader-0.10.5+build.213-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Linguardium** [comment]
Mod does not support 1.16.3
