### ISSUE TITLE
Incompatible with PureBDCraft

### ISSUE THREAD

**Issue by MeeniMc** [Linguardium/ItemNbtModels#9]
Thanks for this very needed piece of addon!

Resource pack PureBDCraft ; https://bdcraft.net/downloads/ ; causes the following issue about missing the 'type' property, that prevents loading the pack altogether.

Obviously the pack works as intended with Optifine, so maybe that type property is not that critical. In any case, the error should be a warning, and not impact the rest of the resource pack loading. 

```
[11:29:34] [Worker-Main-13/INFO]: [ItemNbtModels] Loading properties files from optifine/cit/
[11:29:34] [Worker-Main-13/ERROR]: [ItemNbtModels] Failed to load minecraft:optifine/cit/elytra/broken_elytra.properties due to incompatible or missing type property.
[11:29:34] [main/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: begin 3, end 0, length 0
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.StringIndexOutOfBoundsException: begin 3, end 0, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:3734) ~[?:?]
	at java.lang.String.substring(String.java:1903) ~[?:?]
	at java.lang.String.substring(String.java:1876) ~[?:?]
	at mod.linguardium.itemnbtmodels.compat.CITParser.LoadPropertiesFiles(CITParser.java:89) ~[itemnbtmodels-0.1.1.jar:?]
	at net.minecraft.class_1088.handler$zhk000$applyCITModelPredicates(class_1088.java:621) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1088.<init>(class_1088.java:230) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1092.method_18178(class_1092.java:52) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_1092.method_18789(class_1092.java:19) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_4080.method_18791(class_4080.java:11) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	... 6 more
[11:29:36] [main/INFO]: Reloading ResourceManager: Default, Advancements Enlarger, AppleSkin, Armor Visibility, Auto Config v1 Updated, BeaconFlight, BetterF3, Better Graves, Blur (Fabric), Break Progress, Caelus API, Carpet Mod in Fabric, Carpet Extra, Chat Up!, CleanCut, Clear Skies, ClickThrough, Cloth Config v4, Colormatic, Colytra, Dark Loading Screen, Giselbaers Durability Viewer, Dynamic FPS, EasierCrafting, EasierVillagerTrading, Fabric API, Fabric API Base, Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen Handler API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Loader, Fabric Tailor, FairEnchanting, FallingTree, FlightHelper, Flight HUD, GBfabrictools, Horse Info, I Am Very Smart, ItemNbtModels, Item Scroller, Jankson, LambDynamicLights, Litematica, Lithium, MaLiLib, megane, megane-api, megane-impl, megane-runtime, MiniHUD, Mini Tweaks, Mod Menu, Overpowered Mending, PeacefulSurface, Phosphor, Quick Shulker, ReAuth, Satin, Sodium, SpruceUI, ToroHealth Damage Indicators, Tweakeroo, Villager Names, Hwyla, Xaero's Minimap, Xaero's World Map
[11:29:36] [main/INFO]: [STDOUT]: Inject generated resource packs.
[11:29:37] [Worker-Main-10/WARN]: Unable to resolve texture reference: #missing in bettergraves:block/better_grave
[11:29:38] [Worker-Main-10/INFO]: [ItemNbtModels] Loading properties files from optifine/cit/
[11:29:38] [Worker-Main-10/INFO]: [ItemNbtModels] Finished loading properties files.
[11:29:38] [main/INFO]: OpenAL initialized.
[11:29:38] [main/INFO]: Sound engine started
[11:29:38] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[11:29:38] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[11:29:38] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[11:29:38] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[11:29:38] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[11:29:38] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[11:29:38] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[11:29:38] [main/WARN]: Method overwrite conflict for getSprite in xaerominimap.mixins.json:MixinBakedQuad, previously written by me.jellysquid.mods.sodium.mixin.core.pipeline.MixinBakedQuad. Skipping method.
[11:29:38] [main/WARN]: Method overwrite conflict for getSprite in xaeroworldmap.mixins.json:MixinBakedQuad, previously written by me.jellysquid.mods.sodium.mixin.core.pipeline.MixinBakedQuad. Skipping method.
[11:29:38] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[11:29:38] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[11:29:38] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[11:30:06] [main/INFO]: Stopping!
```

**Comment by Arbee4ever** [comment]
This mod isnt compatible with optifine models
